### ISSUE TITLE
开启 watch + md5 时会出现 map.json 中找不到对应的 sass

### ISSUE THREAD

**Issue by nimojs** [lwdgit/fis-parser-sass2#1]
https://github.com/fex-team/fis-parser-sass/issues/30#issuecomment-136287076

> @nimojs fis-parser-sass 之所以基于 fis-sass 是因为当时编译机上安装不上，所以自己包装了下 lib-sass 库，我觉得 fis-parser-sass2 我觉得只要处理好两个事情应该就能用了：

保存缓存依赖。比如 b.scss @import 了 a.scss, 需要把 b 的 cache 对象里面标记依赖 a. 标记后， watch 的时候， a 文件变化，会触发 b 文件重新编译。
路径问题，比如 a.scss 文件里面引用了某个图片，但是是相对与 a.scss 文件，如果其他目录下面的 scss 文件 @import 了 a.scss， 路径应该没有修改过来。
关于以上两个功能，可以参考 fis-parser-sass

**Comment by lwdgit** [comment]
谢谢你的反馈, 已经纠正了这些错误,请帮忙测试一下,最新版是fis-parser-sass2@1.1.5

**Comment by nimojs** [comment]
```
var sass = require('./node-sass');
```
用相对路径是因为什么？

---

```
sudo npm install -g fis-parser-sass2@1.1.5
```
```
console.log(require('fis-parser-sass2'))
```
```
Error: Cannot find module './node-sass'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/nimojs/node_modules/fis-parser-sass2/index.js:11:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

修改
```
var sass = require('node-sass'); 
```
就可以运行了

**Comment by lwdgit** [comment]
ok
